#### Python Basics-1

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b=np.array([[56,56,56],[57,57,57]])
b

array([[56, 56, 56],
       [57, 57, 57]])

In [12]:
c=np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [56, 56, 56],
       [57, 57, 57]])

In [14]:
c=np.append(a,b)
c

array([ 1,  2,  3,  4,  5,  6, 56, 56, 56, 57, 57, 57])

In [18]:
c=np.stack((a,b))
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[56, 56, 56],
        [57, 57, 57]]])