#### Python Basics-2

In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [25]:
a=np.array([[1,2,3],[4,5,6]],dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
a.shape

(2, 3)

In [17]:
a=np.ones([2,2],dtype=int)
a

array([[1, 1],
       [1, 1]])

In [19]:
a=np.zeros([2,2])
a

array([[0., 0.],
       [0., 0.]])

In [20]:
a=np.zeros([2,2],dtype=int)
a

array([[0, 0],
       [0, 0]])

In [21]:
x1=[1,2,3]
type(x1)

list

In [22]:
np.asarray(x1,dtype=int)

array([1, 2, 3])

In [28]:
a=np.arange(1,16,6)
a

array([ 1,  7, 13])

In [30]:
a=np.linspace(1,16,50)
a

array([ 1.        ,  1.30612245,  1.6122449 ,  1.91836735,  2.2244898 ,
        2.53061224,  2.83673469,  3.14285714,  3.44897959,  3.75510204,
        4.06122449,  4.36734694,  4.67346939,  4.97959184,  5.28571429,
        5.59183673,  5.89795918,  6.20408163,  6.51020408,  6.81632653,
        7.12244898,  7.42857143,  7.73469388,  8.04081633,  8.34693878,
        8.65306122,  8.95918367,  9.26530612,  9.57142857,  9.87755102,
       10.18367347, 10.48979592, 10.79591837, 11.10204082, 11.40816327,
       11.71428571, 12.02040816, 12.32653061, 12.63265306, 12.93877551,
       13.24489796, 13.55102041, 13.85714286, 14.16326531, 14.46938776,
       14.7755102 , 15.08163265, 15.3877551 , 15.69387755, 16.        ])

In [32]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
l=a[2:9:2]
l

array([2, 4, 6, 8])

In [44]:
l=a[2:19:2]
#l
a[l]

array([2, 4, 6, 8])

In [49]:
a=np.array([1,2,np.nan,'k'],dtype=object)
a

array([1, 2, nan, 'k'], dtype=object)

In [60]:
b=np.zeros((3,3),dtype=int)
a=np.ones((3,3),dtype=int)
np.concatenate((a,b))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
c=np.stack((a,b))
c

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [66]:
c.shape

(2, 3, 3)

In [74]:
d=np.hstack((a,b))
d

In [80]:
d

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0]])

In [75]:
d.shape

(3, 6)

In [78]:
e=np.vstack((a,b))
e.shape

(6, 3)